version: '1'
services:
  backend:
    build:
      context: ./speedy-shop
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - app-network

  frontend:
    build:
      context: ./Shards-Dashboard-Lite-React-1.0.0/Source Files
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    networks:
      - app-network

networks:
  app-network: